spring:
  application:
    name: identity-service
  config:
    import: optional:configserver:http://localhost:6969
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
server:
  port: 8001
logging:
  level:

    com.example.identityservice.client: DEBUG
    okhttp3: DEBUG
