authorizationUrl: http://localhost:8001/oauth2/authorize
tokenUrl: http://localhost:8001/oauth2/token
server: http://localhost:8888/credit-service
DB_USERNAME: root
DB_PASSWORD: root
DB_URL: jdbc:mysql://localhost:3306/credit-service
REQUEST_BASIC-AUTH_USERNAME: credit
REQUEST_BASIC-AUTH_PASSWORD: 123456