DB_PASSWORD: root
DB_USER: root
DB_URL: jdbc:mysql://localhost:3306/identity-service
EUREKA_URI: http://localhost:8761/eureka
INTERNAL_NOTIFICATIONS-SERVICE_CREDENTIALS_USER: admin
INTERNAL_NOTIFICATIONS-SERVICE_CREDENTIALS_PASSWORD: 123
OPENFEIGN_ENABLE_OKHTTP: true
OPENFEIGN_NOTIFYCATIONS-SERVICE-CONNECT_TIMEOUT: 5000
OPENFEIGN_NOTIFYCATIONS-SERVICE-READ_TIMEOUT: 5000