spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: credit-service
              uri: lb://credit-service
              predicates:
                - Path=/credit-service/**
              filters:
                - RewritePath=/credit-service/?(?<segment>.*),/$\{segment}
                - DedupeResponseHeader=Access-Control-Allow-Origin
            - id: content-service
              uri: lb://content-service
              predicates:
                - Path=/content-service/**
              filters:
                - RewritePath=/content-service/?(?<segment>.*),/$\{segment}
                - DedupeResponseHeader=Access-Control-Allow-Origin
            - id: identity-service
              uri: lb://identity-service
              predicates:
                - Path=/identity-service/**
              filters:
                - RewritePath=/identity-service/?(?<segment>.*),/$\{segment}
                - DedupeResponseHeader=Access-Control-Allow-Origin
          globalcors:
            cors-configurations:
              '[/**]':
                 allowedOrigins: "*"
                 allowedMethods: "*"
                 allowedHeaders: "*"


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
server:
  port: 8888