spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: C:\Users\Admin\Music\dev-sharing\config-sever\src\main\java\com\example\configsever\config
server:
  port: 6969