spring:
  application:
    name: rating-service
  config:
    import: configserver:http://localhost:6969
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 10
        max-interval: 2000
        multiplier: 1.1
        initial-interval: 1000
      request-connect-timeout: 5000
      request-read-timeout: 5000
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
server:
  port: 8010