spring:
  application:
    name: credit-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8001
  config:
    import: optional:configserver:http://localhost:6969
server:
  port: 8002

